### PR TITLE
Guy/fix bug

### PR DESCRIPTION
**Pull request by guyyoo**
https://github.com/digi-serve/kitchensink_app/issues/34

## Release Notes

- Fix definitions.
- Improve test.

### CODE REVIEW

**Comment by Achoobert** [comment]
Why would ''label' be part of the list? I'm so confused
```
expect($data.text(), "Data value").to.contain("label");
expect($data.text(), "Data value").to.contain("Record A");
expect($data.text(), "Data value").to.contain("Record B");
 ```
 The problem is... I manually ran it again and got this:
 I don't understand why. Also don't understand why it isn't running at all for this pr? 
image

**Comment by Achoobert** [comment]
I think if you add this to `/test_setup/sql/reset_tables.sql` it will make the test way more reliable
On re-run my local gets weird diconnects of the data, because the record isn't actually getting created by the test
Still don't understand what is happening with the label record.....
```
LOCK TABLES `AB_testkcsonCreate` WRITE;
TRUNCATE TABLE `AB_testkcsonCreate`;
UNLOCK TABLES;
```

**Comment by Achoobert** [comment]
Oh, its because of this filter: "label" contains "A"
Apperently I changed the test to match that goofy logic.
image

Fix would be updating that filter to `contains "Record A"`

**Comment by guyyoo** [comment]
> 

The label is created by the Process Manager. My guess is that this might be a test to establish a connection via the Process Manager.

It doesn't work on this PR because we need the latest ab_definition_manager (https://github.com/digi-serve/ab_service_definition_manager/pull/52). Another reason is related to the priority of merging.

**Comment by guyyoo** [comment]
> LOCK TABLES `AB_testkcsonCreate` WRITE;
> TRUNCATE TABLE `AB_testkcsonCreate`;
> UNLOCK TABLES;

Okay, thanks!

**Comment by Achoobert** [comment]
LGTM

**Pull request merged**
