### PR TITLE
[add] three connect fields to OnCreate

### PR DESCRIPTION
**Pull request by Achoobert**
The goal here is to test Process Manager's ability to update the connect field.

I have added all types of connect field: however the most important one is the many-many.

Looks like this: 
image

Should look like this:
image

### CODE REVIEW

**Comment by nh758** [comment]
I see this error in process manager when running:
```
DBError: select `appbuilder-admin`.`AB_testkcskeya`.* from `appbuilder-admin`.`AB_testkcskeya` where ( uuid in_data_collection 1f8b9e67-525d-4fa2-8576-4c18e853677f )
```
I don't think we support the "in data collection" filter in the query task now. 
image

**Comment by Achoobert** [comment]
> I see this error in process manager when running:
> 
> ```
> DBError: select `appbuilder-admin`.`AB_testkcskeya`.* from `appbuilder-admin`.`AB_testkcskeya` where ( uuid in_data_collection 1f8b9e67-525d-4fa2-8576-4c18e853677f )
> ```
> 
> I don't think we support the "in data collection" filter in the query task now. image

Hmm. I'll have to take another look. I couldn't set a query as a filter either, nor could I directly build a custom filter outright. Perhaps for this specific test we don't need a filter though

**Comment by Achoobert** [comment]
> "in data collection" filter 

I got rid of that filter in the last commit, the task is now just getting a group of uuids: 
`Task_03diull : get kcs-a m2m : get kcs-a m2m completed successfully`
image


Screenshot from the new process manager UI (which looks super nice!)
image

image

**Comment by guyyoo** [comment]
Hi, I think we need to pluck [label] instead of [PK].
Screen Shot 2565-08-08 at 13 38 20

because this uses a custom foreign key here so we couldn't use [PK] to update the connected field on the record.
Screen Shot 2565-08-08 at 13 35 59

And then, there are going to be added.
Screen Shot 2565-08-08 at 13 52 52

**Review by nh758 — APPROVED** [review]

**Pull request merged**
